version: '3.8'
services:
  frontend-secure:
    build: ./Frontend
    # command: npm run serve -- --public 0.0.0.0:8080 #Use this for hot-reload capabilities
    ports:
      - 8083:8083

  backend-secure:
    build: ./Backend
    depends_on:
      - mariadb
    ports:
      - 8082:8082

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./Database:/var/lib/mysql
      - ./Database/sql_scripts:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306